const localization = {
  normal: "Normal",
  bug: "Inseto",
  dark: "Sombrio",
  dragon: "Dragão",
  electric: "Elétrico",
  fairy: "Fada",
  fighting: "Lutador",
  fire: "Fogo",
  flying: "Voador",
  ghost: "Fantasma",
  grass: "Planta",
  ground: "Terra",
  ice: "Gelo",
  poison: "Veneno",
  psychic: "Psíquico",
  rock: "Pedra",
  steel: "Metálico",
  water: "Água",
};
const colors = {
  normal: "#C4C0B4",
  bug: "#87950C",
  dark: "#413831",
  dragon: "#7361D1",
  electric: "#E08D00",
  fairy: "#E29FE6",
  fighting: "#852816",
  fire: "#CF2C03",
  flying: "#8FA4FF",
  ghost: "#6969AF",
  grass: "#67AF32",
  ground: "#C5A455",
  ice: "#B4EDF8",
  poison: "#924990",
  psychic: "#E25484",
  rock: "#5E491C",
  steel: "#7F8488",
  water: "#3B9BF1",
};

export { localization, colors };
